// Generated by https://quicktype.io
export interface Orders {
    orders: OrderDetails[];
}

export interface OrderDetails {
    id:        string;
    name:      string;
    address:   string;
    city:      string;
    size:      string;
    delivered: string;
    toppings:  Topping[];
    notes:     Note[];
}

export interface Note {
    note: string;
}

export interface Topping {
    topping: string;
}